service: mailless

frameworkVersion: ">=1.41.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  region: us-east-1
  stage: dev
  environment:
    SLACK_URL: ${env:SLACK_URL}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    SLACK_BOTNAME: ${env:SLACK_BOTNAME}

package:
  exclude:
    - __test__
    - .circleci/**
    - .git/**
    - bin/**
    - src/**
    - .*
    - jest*
    - tsconfig.*
    - package-lock.json
    - yarn.lock
    - README.md

functions:
  send:
    handler: dist/index.handler
    events:
      - http:
          path: mail
          method: post
          cors:
            origin: "*"
            maxAge: 86400
          integration: lambda-proxy
